CREATE DATABASE AdminViews;
USE AdminViews;

-- Tablas

CREATE USER 
'AdminViews'@'localhost' 
IDENTIFIED  BY 'AdminViews123$';

GRANT USAGE ON *.* TO 'AdminViews'@'localhost';

ALTER USER 'AdminViews'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON AdminViews.* 
TO 'AdminViews'@'localhost';

FLUSH PRIVILEGES;